"""add ativa to tarefas

Revision ID: 1a3c0d25f174
Revises: cad2f768e090
Create Date: 2026-04-08 10:08:41.398618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1a3c0d25f174'
down_revision: Union[str, None] = 'cad2f768e090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tarefas', sa.Column('ativa', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tarefas', 'ativa')
    # ### end Alembic commands ###
