"""fase2_sem_alteracoes

Revision ID: 276469b0b966
Revises: 3b260749dd0c
Create Date: 2026-04-08 00:22:44.387505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '276469b0b966'
down_revision: Union[str, None] = '3b260749dd0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
