"""init

Revision ID: 3b260749dd0c
Revises: 
Create Date: 2026-04-08 00:16:52.002457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3b260749dd0c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_tarefas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('icone', sa.String(length=50), nullable=True),
    sa.Column('cor_hex', sa.String(length=7), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_categorias_tarefas_id'), 'categorias_tarefas', ['id'], unique=False)
    op.create_table('familias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('codigo_convite', sa.String(length=12), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_familias_codigo_convite'), 'familias', ['codigo_convite'], unique=True)
    op.create_index(op.f('ix_familias_id'), 'familias', ['id'], unique=False)
    op.create_table('recompensas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('familia_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('custo_pontos', sa.Integer(), nullable=False),
    sa.Column('estoque', sa.Integer(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('imagem_url', sa.String(length=500), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['familia_id'], ['familias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recompensas_familia_id'), 'recompensas', ['familia_id'], unique=False)
    op.create_index(op.f('ix_recompensas_id'), 'recompensas', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('familia_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('papel', sa.Enum('responsavel', 'filho', name='papelusuario'), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('pontos_disponiveis', sa.Integer(), nullable=False),
    sa.Column('pontos_acumulados', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['familia_id'], ['familias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_familia_id'), 'usuarios', ['familia_id'], unique=False)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('metas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('familia_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('pontos_alvo', sa.Integer(), nullable=False),
    sa.Column('pontos_atuais', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ativa', 'concluida', 'cancelada', name='statusmeta'), nullable=False),
    sa.Column('bonus_conclusao', sa.Integer(), nullable=False),
    sa.Column('data_limite', sa.DateTime(timezone=True), nullable=True),
    sa.Column('concluida_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['familia_id'], ['familias.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metas_familia_id'), 'metas', ['familia_id'], unique=False)
    op.create_index(op.f('ix_metas_id'), 'metas', ['id'], unique=False)
    op.create_index(op.f('ix_metas_status'), 'metas', ['status'], unique=False)
    op.create_index(op.f('ix_metas_usuario_id'), 'metas', ['usuario_id'], unique=False)
    op.create_table('notificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('tarefa_atribuida', 'tarefa_concluida', 'tarefa_aprovada', 'tarefa_rejeitada', 'meta_atingida', 'resgate_aprovado', name='tiponotificacao'), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('referencia_id', sa.Integer(), nullable=True),
    sa.Column('referencia_tipo', sa.String(length=50), nullable=True),
    sa.Column('lida', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificacoes_criado_em'), 'notificacoes', ['criado_em'], unique=False)
    op.create_index(op.f('ix_notificacoes_id'), 'notificacoes', ['id'], unique=False)
    op.create_index(op.f('ix_notificacoes_lida'), 'notificacoes', ['lida'], unique=False)
    op.create_index(op.f('ix_notificacoes_tipo'), 'notificacoes', ['tipo'], unique=False)
    op.create_index(op.f('ix_notificacoes_usuario_id'), 'notificacoes', ['usuario_id'], unique=False)
    op.create_table('resgates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('recompensa_id', sa.Integer(), nullable=False),
    sa.Column('pontos_gastos', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'aprovado', 'recusado', 'entregue', name='statusresgate'), nullable=False),
    sa.Column('observacao', sa.String(length=300), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recompensa_id'], ['recompensas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resgates_id'), 'resgates', ['id'], unique=False)
    op.create_index(op.f('ix_resgates_recompensa_id'), 'resgates', ['recompensa_id'], unique=False)
    op.create_index(op.f('ix_resgates_status'), 'resgates', ['status'], unique=False)
    op.create_index(op.f('ix_resgates_usuario_id'), 'resgates', ['usuario_id'], unique=False)
    op.create_table('tarefas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('familia_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('criado_por_id', sa.Integer(), nullable=False),
    sa.Column('atribuido_a_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('pontos', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'em_andamento', 'concluida', 'rejeitada', 'expirada', name='statustarefa'), nullable=False),
    sa.Column('data_limite', sa.DateTime(timezone=True), nullable=True),
    sa.Column('concluida_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['atribuido_a_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_tarefas.id'], ),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['familia_id'], ['familias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tarefas_atribuido_a_id'), 'tarefas', ['atribuido_a_id'], unique=False)
    op.create_index(op.f('ix_tarefas_categoria_id'), 'tarefas', ['categoria_id'], unique=False)
    op.create_index(op.f('ix_tarefas_criado_por_id'), 'tarefas', ['criado_por_id'], unique=False)
    op.create_index(op.f('ix_tarefas_familia_id'), 'tarefas', ['familia_id'], unique=False)
    op.create_index(op.f('ix_tarefas_id'), 'tarefas', ['id'], unique=False)
    op.create_index(op.f('ix_tarefas_status'), 'tarefas', ['status'], unique=False)
    op.create_table('transacoes_pontos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tarefa_id', sa.Integer(), nullable=True),
    sa.Column('aprovado_por_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('credito', 'debito', 'bonus', 'expiracao', name='tipotransacao'), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('saldo_apos', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aprovado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tarefa_id'], ['tarefas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transacoes_pontos_aprovado_por_id'), 'transacoes_pontos', ['aprovado_por_id'], unique=False)
    op.create_index(op.f('ix_transacoes_pontos_criado_em'), 'transacoes_pontos', ['criado_em'], unique=False)
    op.create_index(op.f('ix_transacoes_pontos_id'), 'transacoes_pontos', ['id'], unique=False)
    op.create_index(op.f('ix_transacoes_pontos_tarefa_id'), 'transacoes_pontos', ['tarefa_id'], unique=False)
    op.create_index(op.f('ix_transacoes_pontos_tipo'), 'transacoes_pontos', ['tipo'], unique=False)
    op.create_index(op.f('ix_transacoes_pontos_usuario_id'), 'transacoes_pontos', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transacoes_pontos_usuario_id'), table_name='transacoes_pontos')
    op.drop_index(op.f('ix_transacoes_pontos_tipo'), table_name='transacoes_pontos')
    op.drop_index(op.f('ix_transacoes_pontos_tarefa_id'), table_name='transacoes_pontos')
    op.drop_index(op.f('ix_transacoes_pontos_id'), table_name='transacoes_pontos')
    op.drop_index(op.f('ix_transacoes_pontos_criado_em'), table_name='transacoes_pontos')
    op.drop_index(op.f('ix_transacoes_pontos_aprovado_por_id'), table_name='transacoes_pontos')
    op.drop_table('transacoes_pontos')
    op.drop_index(op.f('ix_tarefas_status'), table_name='tarefas')
    op.drop_index(op.f('ix_tarefas_id'), table_name='tarefas')
    op.drop_index(op.f('ix_tarefas_familia_id'), table_name='tarefas')
    op.drop_index(op.f('ix_tarefas_criado_por_id'), table_name='tarefas')
    op.drop_index(op.f('ix_tarefas_categoria_id'), table_name='tarefas')
    op.drop_index(op.f('ix_tarefas_atribuido_a_id'), table_name='tarefas')
    op.drop_table('tarefas')
    op.drop_index(op.f('ix_resgates_usuario_id'), table_name='resgates')
    op.drop_index(op.f('ix_resgates_status'), table_name='resgates')
    op.drop_index(op.f('ix_resgates_recompensa_id'), table_name='resgates')
    op.drop_index(op.f('ix_resgates_id'), table_name='resgates')
    op.drop_table('resgates')
    op.drop_index(op.f('ix_notificacoes_usuario_id'), table_name='notificacoes')
    op.drop_index(op.f('ix_notificacoes_tipo'), table_name='notificacoes')
    op.drop_index(op.f('ix_notificacoes_lida'), table_name='notificacoes')
    op.drop_index(op.f('ix_notificacoes_id'), table_name='notificacoes')
    op.drop_index(op.f('ix_notificacoes_criado_em'), table_name='notificacoes')
    op.drop_table('notificacoes')
    op.drop_index(op.f('ix_metas_usuario_id'), table_name='metas')
    op.drop_index(op.f('ix_metas_status'), table_name='metas')
    op.drop_index(op.f('ix_metas_id'), table_name='metas')
    op.drop_index(op.f('ix_metas_familia_id'), table_name='metas')
    op.drop_table('metas')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_familia_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_recompensas_id'), table_name='recompensas')
    op.drop_index(op.f('ix_recompensas_familia_id'), table_name='recompensas')
    op.drop_table('recompensas')
    op.drop_index(op.f('ix_familias_id'), table_name='familias')
    op.drop_index(op.f('ix_familias_codigo_convite'), table_name='familias')
    op.drop_table('familias')
    op.drop_index(op.f('ix_categorias_tarefas_id'), table_name='categorias_tarefas')
    op.drop_table('categorias_tarefas')
    # ### end Alembic commands ###
