"""add deve_trocar_senha

Revision ID: 7d5057901367
Revises: add_admin_role
Create Date: 2026-04-08 09:31:18.208070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7d5057901367'
down_revision: Union[str, None] = 'add_admin_role'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('deve_trocar_senha', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'deve_trocar_senha')
    # ### end Alembic commands ###
